services:
  # Backend API service
  - type: web
    name: dropship-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: false

  # Frontend static site
  - type: web
    name: dropship-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: dropship-api
          property: url
    autoDeploy: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 